global using Frames.Entities;
global using Frames.Entities.Models;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Frames.Web.Contracts;
global using Frames.Web.Services;
global using Frames.Web.Helpers;
global using Frames.Web.DTOs;
global using System.Linq.Dynamic.Core;
